package Modelos;
// Generated 15-may-2019 12:11:04 by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer idproductos;
     private Categorias categorias;
     private Proveedores proveedores;
     private String referencia;
     private String descripcion;
     private Long precioCompra;
     private Long precioVenta;
     private Integer cantidad;
     

    public Productos() {
    }

	
    public Productos(Categorias categorias, Proveedores proveedores) {
        this.categorias = categorias;
        this.proveedores = proveedores;
    }
    public Productos(Categorias categorias, Proveedores proveedores, String referencia, String descripcion, Long precioCompra, Long precioVenta, Integer cantidad) {
       this.categorias = categorias;
       this.proveedores = proveedores;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.precioCompra = precioCompra;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
    }

   
    public Integer getIdproductos() {
        return this.idproductos;
    }
    
    public void setIdproductos(Integer idproductos) {
        this.idproductos = idproductos;
    }
    public Categorias getCategorias() {
        return this.categorias;
    }
    
    public void setCategorias(Categorias categorias) {
        this.categorias = categorias;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(Long precioCompra) {
        this.precioCompra = precioCompra;
    }
    public Long getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(Long precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


